### PR TITLE
remove deploy step in travis

### PR DESCRIPTION
**Pull request by mnaamani**

### CODE REVIEW

**Comment by siman** [comment]
I didn't work with Travis, so not sure how to review this PR

**Comment by mnaamani** [comment]
I can give you a briefly of what the config is supposed to do:

It uses an OS image prepared with node_js versions 10 and 12. (it will run two separate jobs for each version)
Travis is configured to cache node_modules/ and yarn config/cache between runs, to speedup checks.

The script job runs `yarn && yarn build` if it fails (non 0 exit code returned) it will show up in github as a failed check. Otherwise it passes and we should see:

Screen Shot 2019-05-23 at 1 45 06 PM

Clicking Details show you the [logs](https://travis-ci.org/Joystream/apps/builds/534566388?utm_source=github_status&utm_medium=notification)

If you prefer @jfinkhaeuser can review instead.

**Comment by jfinkhaeuser** [comment]
It looks reasonable to me, yes. And since all checks have passed, I don't see a reason not to merge.

**Comment by mnaamani** [comment]
Merging following approval.

**Pull request merged**
