### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by siman**
fix #137

### CODE REVIEW

**Comment by bwhm** [comment]
Any chance this resolves #136?

**Comment by mnaamani** [comment]
It very likely does, because updated polkadot-js/api which I was about to test until I saw this PR :)

**Comment by siman** [comment]
> Any chance this resolves #136?

yes, it resolves

**Comment by mnaamani** [comment]
Nice work on this Alex, I'll test and confirm. Hope there weren't too many tough merge conflicts to resolve?

**Pull request merged**
